name: innochat
description: A creative social app with Firebase integration.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  flutter_spinkit: ^5.2.0
  animate_do: ^4.2.0
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.2
  share_plus: ^11.0.0
  image_picker: ^1.0.4
  video_player: ^2.8.2
  cached_network_image: ^3.4.1
  email_validator: ^3.0.0
  path_provider: ^2.1.4
  flutter_emoji: ^2.5.1
  emoji_picker_flutter: ^4.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icon/icon.png"  # Using the same file for simplicity
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/