name: innochat
description: A creative social app with Firebase integration.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.3.3

  # UI and styling
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  animate_do: ^4.2.0
  fluttertoast: ^8.2.2

  # Media and file handling
  image_picker: ^1.0.4
  file_picker: ^8.1.3
  video_player: ^2.8.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  flutter_pdfview: ^1.3.2
  open_file: ^3.3.2
  http: ^1.1.0
  crypto: ^3.0.3
  webview_flutter: ^4.4.2
  dio: ^5.3.2

  # Emoji support
  flutter_emoji: ^2.5.1
  emoji_picker_flutter: ^4.3.0

  # Sharing and downloads
  share_plus: ^11.0.0
  url_launcher: ^6.3.0

  # Other utilities
  email_validator: ^3.0.0
  intl: ^0.19.0

  # App icons
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
